name: My secrets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubunto-latest

    steps:
      - shell: bash
        env:
           UN: ${{ secrets.USER_NAME }}
        run: |
           echo "$UN"
